version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 -w 4 --log-level=debug wsgi:app 
    ports:
      - 5000:5000
    environment:
      - FLASK_SECRET=pass
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:pass@db:5432/postgres
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 50M
  locust:
    build:
      context: ./load_testing
      dockerfile: Dockerfile
    command: locust
    ports:
      - 8089:8089
